/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package org.michaeldadams.bibscrape.main

class MessageUtils {
  companion object {
    fun getMessage(): String = "Hello      World!"
  }
}
