package org.michaeldadams.gradle

import org.gradle.api.Plugin
import org.gradle.api.Project
import org.gradle.api.artifacts.ExternalDependency
import org.gradle.api.tasks.SourceSet
import org.jetbrains.kotlin.gradle.dsl.KotlinJvmProjectExtension
import java.text.SimpleDateFormat
import java.util.Date

// ////////////////////////////////////////////////////////////////
// Set the version based on Git tags
// Create a new version with: git tag -a v2023.01.01
class GenerateBuildInformationPlugin : Plugin<Project> {
  override fun apply(project: Project) {
    val kotlin = project.extensions.getByType(KotlinJvmProjectExtension::class.java)
    val task = project.tasks.register("generateBuildInformation") {
      // TODO: description = "Displays the project version."
      // group = "Help"
      doLast {
        fun String.escape() = """([\\\"\$])""".toRegex().replace(this, """\\$1""")

        val dependencies = project.configurations
          .flatMap { it.dependencies }
          .filterIsInstance<ExternalDependency>()
          .map {
            val key = "${it.group?.escape()}:${it.name.escape()}:${it.version?.escape()}"
            val value = "${it.targetConfiguration?.escape() ?: "default"}"
            "    \"${key}\" to \"${value}\","
          }.sorted()
          .joinToString("\n")

        val systemProperties = System.getProperties().toList()
          .filter { it.first.toString().matches("(java|os)\\..*".toRegex()) } // TODO: why filter?
          .map { "    \"${it.first?.toString()?.escape()}\" to \"${it.second?.toString()?.escape()}\"," }
          .sorted()
          .joinToString("\n")

        fun field(fieldName: String, value: Any?): String =
          "  val ${fieldName.trim()}: String${if (value == null) "?" else ""} = ${value?.let { "\"${it.toString().escape()}\"" } ?: "null"}"

        // TODO: configurable package
        // TODO: configurable options Pair(name, value)
        val code = """
          |// Do not edit this file by hand.  It is generated by `gradle`.
          |package org.michaeldadams.bibscrape
          |
          |import javax.annotation.processing.Generated
          |
          |/** Information about the build and build-time environment */
          |@Generated("org.michaeldadams.gradle.GenerateBuildInformationPlugin")
          |object BuildInformation {
          |${field("group         ", project.group)}
          |${field("name          ", project.name)}
          |${field("version       ", project.version)}
          |${field("description   ", project.description)}
          |${field("kotlinVersion ", kotlin.coreLibrariesVersion)}
          |${field("kotlinPlatform", kotlin.target.platformType)}
          |${field("javaVersion   ", System.getProperty("java.version"))}
          |${field("gradleVersion ", project.gradle.gradleVersion)}
          |${field("buildTime     ", SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ss.SSSXXX").format(Date()))}
          |${field("status        ", project.status)}
          |${field("path          ", project.path)}
          |
          |  /** Build-time dependencies and their target configurations */
          |  val dependencies: List<Pair<String, String>> = listOf(
          |$dependencies
          |  )
          |
          |  /** Build-time system properties and their values */
          |  val systemProperties: List<Pair<String, String>> = listOf(
          |$systemProperties
          |  )
          |
          |  val versionMessage = "${'$'}name version ${'$'}version (https://github.org/ucombinator/jade)"
          |}
          |
        """.trimMargin()

        project.generateSrc("BuildInformation.kt", code)
      }
    }

    // Ensure that generateBuildInformation is called before compilation
    kotlin.sourceSets.getByName(SourceSet.MAIN_SOURCE_SET_NAME).kotlin.srcDir(task)
  }
}
